### ISSUE TITLE
Wrap-up roadmap

### ISSUE THREAD

**Issue by wustep** [wustep/chorus#1]
Wrapping up Chorus with a presentation at the Denman + Writeup

**Features** 
- [x] Custom commands (like noteOn / noteOff on MIDI Demo)
- [ ] QR Code to scan to auto-join room? Add styling example of this at the bottom-right. 

**SpaceTime**
- [ ] Add in remaining crossfiltered settings in sync
- [ ] Double check on if Chromecasted version shows the blue / red heatmap correctly? See #chrous, seems to be a CSS3 translate3d problem or something

**Documentation**
- [ ] Port old chorus demos to v1
  - [X] MIDI
  - [x] Leaflet
  - [ ] Crossfilter
- [ ] Completed README about Chorus and its demos code
- [X] Add more comments to server & client code
- [ ] Extended documentation
  - [X] Basic Counter
  - [ ] Crossfilter Airplane Dashboard
  - [ ] Leaflet
  - [x] MIDI
- [ ] Article write-up about what Chorus is, how to set it up, styling, etc.

**Denman Undergraduate Forum (April 3, 2018)**
- [x] Poster
- [X] Set up environment for chorus demos, DNS / domain, etc. 
   - Done on AWS
- [x] Test & finalize demo logistics 
  - [X] Devices: 1 laptop, 1 phone, 1 iPad
  - [x] Ensure all demos work and decide which ones (probably MIDI, Leaflet, Spacetime?)
  - [x] Intro page with squares linking to demos

**Expansion**
- Consider looking into another feature to add novelty, like Meraj Flux capacitor as middleware
